from metrics.exporter import MetricsCollector
from sim.reporting import summarize_report

def test_metrics_collector_matches_report_assumptions():
    collector = MetricsCollector()
    collector.record_forwarded("telemetry")
    collector.record_expired("science", "sci-001")
    collector.set_queue_depth("queue_depth_lunar", 5)
    
    snap = collector.snapshot()
    
    # Ensure keys generated by metrics collector match what reporting expects
    assert "bundles_forwarded_total" in snap
    assert "bundles_delivered_total" in snap
    assert "bundles_stored_total" in snap
    assert "bundles_expired_total" in snap
    assert "purged_bundle_ids" in snap
    assert "last_queue_depths" in snap
    
    assert snap["purged_bundle_ids"] == ["sci-001"]
    assert snap["last_queue_depths"]["queue_depth_lunar"] == 5

    # Mock a simulator report using this snapshot
    mock_report = {
        "scenario_name": "test",
        "final_metrics": snap,
        "purged_bundle_ids": snap["purged_bundle_ids"]
    }
    
    summary = summarize_report(mock_report)
    assert summary["forwarded_total"] == 1
    assert summary["expired_total"] == 1
    assert summary["purged_count"] == 1